"""Entropy task generation and package autobootstrap helpers."""

from __future__ import annotations

from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Callable


def slugify(text: str) -> str:
    import re

    slug = re.sub(r"[^a-z0-9]+", "-", text.lower()).strip("-")
    return slug or "cleanup"


def entropy_candidates(
    findings: list[Any],
    *,
    max_files_per_task: int,
    max_tasks: int,
) -> list[dict[str, Any]]:
    by_file: dict[str, list[Any]] = {}
    for finding in findings:
        by_file.setdefault(finding.file, []).append(finding)

    def score(item: tuple[str, list[Any]]) -> tuple[int, int, str]:
        file, file_findings = item
        fail_count = sum(1 for finding in file_findings if finding.severity == "fail")
        return (-fail_count, -len(file_findings), file)

    ordered_files = [file for file, _ in sorted(by_file.items(), key=score)]
    chunks: list[list[str]] = []
    current: list[str] = []
    for file_path in ordered_files:
        current.append(file_path)
        if len(current) >= max_files_per_task:
            chunks.append(current)
            current = []
        if len(chunks) >= max_tasks:
            break
    if current and len(chunks) < max_tasks:
        chunks.append(current)

    tasks: list[dict[str, Any]] = []
    for idx, files in enumerate(chunks, start=1):
        task_findings = [finding for finding in findings if finding.file in files]
        rules = sorted({finding.rule for finding in task_findings})
        tasks.append(
            {
                "name": f"Entropy cleanup #{idx}",
                "files": files,
                "rules": rules,
                "findingCount": len(task_findings),
                "action": (
                    "Apply tiny non-behavioral refactors for listed files only. "
                    "Keep each PR scoped and verify checks pass."
                ),
            }
        )
    return tasks


def write_entropy_task(
    root: Path,
    findings: list[Any],
    *,
    max_files_per_task: int,
    max_tasks: int,
    now_iso: Callable[[], str],
    write_text: Callable[[Path, str], None],
) -> Path:
    task_dir = root / "docs" / "planning" / "work" / "background"
    task_dir.mkdir(parents=True, exist_ok=True)
    task_id = datetime.now(timezone.utc).strftime("%Y%m%d%H%M%S")
    task_path = task_dir / f"{task_id}-entropy-cleanup-TASK.md"
    candidates = entropy_candidates(
        findings,
        max_files_per_task=max_files_per_task,
        max_tasks=max_tasks,
    )

    lines = [
        f"# Background Task: {task_id}",
        "",
        "## Request",
        "Continuous entropy cleanup: open tiny refactor PR(s) for invariant drift/slop patterns.",
        "",
        "## Status",
        "Queued",
        "",
        "## Started",
        now_iso(),
        "",
        "## Constraints",
        f"- Max files per cleanup task: {max_files_per_task}",
        f"- Max tasks this run: {max_tasks}",
        "- Non-behavioral refactors only",
        "- Keep commits/PRs small and focused",
        "",
        "## Candidate Tasks",
        "",
    ]
    if not candidates:
        lines.extend(["- No candidates found.", ""])
    else:
        for task in candidates:
            lines.append(f"### {task['name']}")
            lines.append(f"- Files: {', '.join(f'`{file}`' for file in task['files'])}")
            lines.append(f"- Rules: {', '.join(f'`{rule}`' for rule in task['rules']) if task['rules'] else '[none]'}")
            lines.append(f"- Findings: {task['findingCount']}")
            lines.append(f"- Action: {task['action']}")
            lines.append("")

    lines.extend(
        [
            "## Log",
            "- Generated by `python3 .cnogo/scripts/workflow_checks.py entropy --write-task`",
            "",
        ]
    )
    write_text(task_path, "\n".join(lines))
    return task_path


def autobootstrap_packages_if_empty(
    root: Path,
    wf: dict[str, Any],
    *,
    cmd: str,
    timeout_sec: int,
    packages_from_workflow: Callable[[dict[str, Any]], list[dict[str, Any]]],
    run_shell: Callable[..., tuple[int, str]],
    load_workflow: Callable[[Path | None], dict[str, Any]],
    print_fn: Callable[[str], None] = print,
) -> dict[str, Any]:
    """Auto-populate WORKFLOW packages[] for review/verify-ci when empty."""
    if cmd not in {"review", "verify-ci"}:
        return wf
    if packages_from_workflow(wf):
        return wf
    detect_script = root / ".cnogo" / "scripts" / "workflow_detect.py"
    if not detect_script.exists():
        return wf

    print_fn("⚠️  No packages configured; attempting auto-detect via workflow_detect.py ...")
    detect_timeout = max(20, min(timeout_sec, 120))
    rc, out = run_shell(
        "python3 .cnogo/scripts/workflow_detect.py --write-workflow",
        cwd=root,
        timeout_sec=detect_timeout,
    )
    if rc != 0:
        tail = "\n".join(line for line in out.splitlines()[-3:] if line.strip())
        print_fn("⚠️  Auto-detect failed; continuing with existing WORKFLOW.json.")
        if tail:
            print_fn(tail)
        return wf

    refreshed = load_workflow(root)
    refreshed_packages = packages_from_workflow(refreshed)
    if refreshed_packages:
        print_fn(f"✅ Detected {len(refreshed_packages)} package(s) and updated WORKFLOW.json.")
        return refreshed
    print_fn("⚠️  Auto-detect ran, but packages[] is still empty.")
    return refreshed
